Update MySQLPlugin.cpp
callofduty4x/mysql pull request #9
Opened 2018-01-27 10:51 UTC by thamidu

In some query like the one below, the columns may return NULL values which will cause segmentaion issue shutdowns. So as the discussion in [issue 7](https://github.com/callofduty4x/mysql/issues/7), I suggest to push an empty string or undefined.

Ex query:

```
SELECT MAX(player_score) AS max_score, COUNT(player_id) AS player_cnt
FROM table
WHERE condition 
```

If there is no record in the table, the column max_score will be NULL and player_cnt will be zero. This will probably cause segmentaion issues. So pushing undefined or empty string if some column has NULL value can fix the segmentation error.

2018-01-28 21:47 UTC, T-Maxxx requested changes

2018-01-28 21:47 UTC, T-Maxxx commented on MySQLPlugin.cpp
> +                Plugin_Scr_AddString("");
Empty string may be a result in a row's query. So I suggest to add `undefined` value to determine whether there are something wrong with query result.
Actually, a nice catch.

2018-01-28 21:47 UTC, T-Maxxx commented on MySQLPlugin.cpp
> +            }
This is C++ and only one expression in block of code, so there's no need in additional brackets.

2018-01-29 11:18 UTC, thamidu commented on MySQLPlugin.cpp
> +                Plugin_Scr_AddString("");
Yah... Got it and thanks.

2018-01-29 11:33 UTC, thamidu commented on MySQLPlugin.cpp
> +                Plugin_Scr_AddString("");
Yah... Got it.
And you have already caught that in issue 7. I just gave an example.  😊

2018-01-29 19:24 UTC, merged